### ISSUE TITLE
canvas-datagrid crashed after cell.innerHTML property gets non-latin symbols

### ISSUE THREAD

**Issue by Imperat** [TonyGermaneri/canvas-datagrid#127]
### Expected behavior and actual behavior.
Try to double click some cell and input some text in Russian: "Спартак чемпион!"
Expected result: text saved
Actual result: Exception raised in console and view is broken

### Specifications like the version of the project, operating system, or hardware.
Chrome Version 59.0.3071.86 (Official Build) (64-bit), Ubuntu 16.04

**Comment by TonyGermaneri** [comment]
Oh wow.  I've never tired editing a cell with Russian in it.  I'll file this as a bug and get it fixed.

**Comment by TonyGermaneri** [comment]
I'm not able to reproduce this error.  I'm able to enter the text you provided into an inout.  I'm not using Ubuntu, I'm using OSX.  Can you tell me what the exception is?  Maybe I can figure it out just based on that.

Proof I really did try:
http://h.dropcanvas.com/tvpaf/Screen%20Shot%202018-06-10%20at%209.53.09%20PM.png

I'll try again using whatever emulators I can dig up.

**Comment by Imperat** [comment]
Thank you for checking!
I try to reproduce it and found right way to do it. This bug related to cell.innerHTML property.
For example try to use next line of code:
```
  grid.addEventListener('rendercell', function (e) {
        e.cell.innerHTML = '<div>Спартак чемпион</div>';
    });
```
Sorry for confusing, I didn't know that this is specific for innerHTML property, not for common library behaviour.

**Comment by Imperat** [comment]
Error log is:
```
/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at n (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:18754)
    at eval (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:29626)
    at y (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:30407)
    at eval (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:32943)
    at Object.e.draw (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:33246)
    at Object.e.endEdit (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:120075)
    at HTMLCanvasElement.e.click (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:54456)
```

**Comment by Imperat** [comment]
I make temporary solution for this in my code with next way:
```
      const errorDiv = `<div style="display: inline-block; margin-left: 5px; font-size: 10px; bottom: 2px;">${cell.error}</div>`;
      const valueDiv = value ? `<div style="display: inline-block;">${value}</div>` : '';

      try {
        btoa(value);
        cell.innerHTML = `${valueDiv}${errorDiv}`;
      } catch (e) {
        cell.innerHTML = errorDiv;
      }
```
but it new error appears if value contain '&' symbol:
```
Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at n (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:18575)
    at eval (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:29626)
    at y (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:30407)
    at eval (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:32943)
    at Object.e.draw (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:33246)
    at HTMLCanvasElement.e.mousemove (/node_modules/canvas-datagrid/dist/canvas-datagrid.js:9:54088)
```

**Comment by TonyGermaneri** [comment]
Oh wow!  Any reason you're not using `cell.value`?  You only need to use the `innerHTML` property if you're trying to draw HTML onto the canvas.  `cell.value` is much, much, cleaner and faster.

I changed the name of the issue to reflect that the bug is related to `innerHTML` and not input (although input is how it got in).

**Comment by Imperat** [comment]
Hi, @TonyGermaneri. Thank you for you quickly answer.
In my business logic I have some validation rules for few columns. For example I need to check that in column "AC" there is valid url string.
If user input invalid url string I draw the cell in red color, write string in one div and error message in another div (with more smaller font). It will be too helpful if you have idea how to implement it without using innerHTML property :) Now I have no idea :(

**Comment by Imperat** [comment]
It's impossible just to disallow user to write invalid strings, because of he imports data from excel or csv file and I need to show a lot of validation errors (if he has it of course)

**Comment by TonyGermaneri** [comment]
Yeah, wow, it's not something I ever considered.  It may be useful to implement some basic HTML commands that can be interpreted by the lib.  Let me research a bit on how to add this as a feature in the native canvas text.

**Comment by TonyGermaneri** [comment]
As far as fixing the immediate problem of characters throwing errors: you can probably fix this by determining the correct encoding method for the Cyrillic characters.

```
var grid = canvasDatagrid({
    parentNode: parentNode,
    data: [
        {col1: 'Спартак чемпион!', col2: 0, col3: 'a'}
    ]
});
grid.schema[0].type = 'html';
grid.formatters.html = function (cell) {
    return unescape(encodeURIComponent('<div style="color: red;">' + cell.value + '</div>'));
}
```

Basically anything going into `innerHTML` needs to pass through `unescape(encodeURIComponent())` to ensure it is always `Latin1`.


Успех!

You can use a formatter function to reformat the non-ascii text into ascii text with html entity encoding for the non-ascii characters.

**Comment by Imperat** [comment]
Thank you a lot! I'll try to use it tomorrow :)

**Comment by TonyGermaneri** [comment]
I looked at added this but the spec basically says that when you're using Latin1 the Cyrillic characters always have to go through the enc/dec function, since I can't detect in any nice way if people are passing non-Latin1 and they can specify their own character set as well as use the above work around I'm going to just create a tutorial that describes how to change character sets and use the workaround if you're stuck in latin1, but I don't think modifying the source is helpful.
